/**
 * Meridian domain contracts.
 *
 * Everything else in the app is written against these types. Kept free of React,
 * Dexie and three.js so the game rules stay independently testable.
 */

/** A [longitude, latitude] pair in degrees. Always lon-first, matching GeoJSON. */
export type LonLat = readonly [number, number];

/** The three modes (PRD §2). Never mixed within a round. */
export type GameMode = 'country' | 'capital' | 'flag';

export const GAME_MODES: readonly GameMode[] = ['country', 'capital', 'flag'] as const;

/** Daily Challenge vs. Practice (PRD §3). */
export type PuzzleKind = 'daily' | 'practice';

/** Where a round is in its lifecycle. */
export type RoundStatus =
  /** Accepting guesses. */
  | 'playing'
  /** Guessed correctly — the reveal plays, and the result counts toward the streak. */
  | 'solved'
  /** Gave up — the reveal plays, but the round does not count as a win. */
  | 'revealed';

/**
 * One playable country. Generated by scripts/build-data.mjs; see that file for how
 * each field is derived and which Natural Earth hazards it works around.
 */
export interface Country {
  /** ISO 3166-1 numeric, zero-padded. Joins to the topology's feature ids. */
  readonly id: string;
  /** ISO 3166-1 alpha-2, lowercase. Names the flag asset: `/flags/{cca2}.svg`. */
  readonly cca2: string;
  /** ISO 3166-1 alpha-3, uppercase. Used in share text and as a stable stats key. */
  readonly cca3: string;
  /** Common English name — the clue in Country mode. */
  readonly name: string;
  readonly official: string;
  /** Primary capital — the clue in Capital mode. Null only if the source lists none. */
  readonly capital: string | null;
  /** Every capital the source lists (South Africa has three). */
  readonly capitals: readonly string[];
  /** Main-cluster centroid longitude — the country's game location. */
  readonly lon: number;
  /** Main-cluster centroid latitude — the country's game location. */
  readonly lat: number;
  readonly areaKm2: number;
  readonly region: string;
  readonly subregion: string;
  /** False only for countries with no geometry at 50m (Tuvalu) — marker-only. */
  readonly hasPolygon: boolean;
  /** Too small to tap reliably at world zoom; the renderer gives it a marker. */
  readonly micro: boolean;
}

/** One recorded guess and everything derived from it at the moment it was made. */
export interface Guess {
  /** The country the player clicked. */
  readonly countryId: string;
  /** Great-circle distance from the guessed centroid to the target's, in km. */
  readonly distanceKm: number;
  /** Initial great-circle bearing from the guess toward the target, degrees clockwise from north. */
  readonly bearingDeg: number;
  /** True if this guess was the answer. */
  readonly correct: boolean;
}

/** A puzzle: what to find, in which mode, on which day. */
export interface Puzzle {
  readonly mode: GameMode;
  readonly kind: PuzzleKind;
  /** Local calendar day as `YYYY-MM-DD`. For practice, the day it was generated. */
  readonly dateKey: string;
  /** The country the player must locate. */
  readonly targetId: string;
  /**
   * Distinguishes successive practice rounds on the same day so they get separate
   * saved state. Always 0 for daily puzzles, which are one-per-day by definition.
   */
  readonly seq: number;
}

/** Everything about a round in progress or just finished. */
export interface RoundState {
  readonly puzzle: Puzzle;
  readonly guesses: readonly Guess[];
  readonly status: RoundStatus;
  /**
   * The smallest error across all guesses so far, in km, and undefined before the
   * first guess. Monotonically non-increasing: it sets how narrow the heatmap's
   * contour bands are drawn, so the field tightens as the player closes in (PRD §4).
   */
  readonly fieldRadiusKm: number | undefined;
}

/** Per-mode Daily Challenge streak and history (PRD §3). */
export interface ModeStats {
  /** Primary key: the mode this row tracks. */
  readonly mode: GameMode;
  readonly currentStreak: number;
  readonly maxStreak: number;
  /** `YYYY-MM-DD` of the most recent solved daily, used to detect a broken streak. */
  readonly lastSolvedDate: string | null;
  readonly dailiesPlayed: number;
  readonly dailiesSolved: number;
  /** Total guesses across solved dailies — with `dailiesSolved`, yields the average. */
  readonly totalGuessesOnSolved: number;
  /** Fewest guesses ever taken to solve a daily in this mode. */
  readonly bestGuessCount: number | null;
  /** Lifetime practice counters, kept separate so practice never moves the streak. */
  readonly practicePlayed: number;
  readonly practiceSolved: number;
  readonly practiceTotalGuessesOnSolved: number;
}

/** A finished round, persisted so a completed daily stays completed across reloads. */
export interface SavedRound {
  /** Primary key: `${kind}:${mode}:${dateKey}:${seq}`. */
  readonly key: string;
  readonly puzzle: Puzzle;
  readonly guesses: readonly Guess[];
  readonly status: RoundStatus;
  /** Epoch ms the round was last written. */
  readonly updatedAt: number;
}

/** Resolved colour ramp stop, as consumed by both the map tint and the globe. */
export interface RampStop {
  readonly at: number;
  readonly rgb: readonly [number, number, number];
}
