// GENERATED by scripts/build-data.mjs — do not edit by hand. Run `npm run data`.
//
// Sources:
//   Boundaries  Natural Earth Admin-0 via world-atlas (public domain)
//   Metadata    world-countries (ODbL)
//   Flags       flagcdn.com, vendored to public/flags by scripts/fetch-flags.mjs
//
// `lon`/`lat` are MAIN-CLUSTER centroids, not raw geometric centroids: detached
// overseas territory is excluded so that distance feedback matches where a player
// actually believes the country is. See the build script for the full rationale.

import type { Country } from '@/types/game';

export const COUNTRIES: readonly Country[] = [
  {
    "id": "004",
    "cca2": "af",
    "cca3": "AFG",
    "name": "Afghanistan",
    "official": "Islamic Republic of Afghanistan",
    "capital": "Kabul",
    "capitals": [
      "Kabul"
    ],
    "lon": 65.9259,
    "lat": 33.8188,
    "areaKm2": 642060,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "008",
    "cca2": "al",
    "cca3": "ALB",
    "name": "Albania",
    "official": "Republic of Albania",
    "capital": "Tirana",
    "capitals": [
      "Tirana"
    ],
    "lon": 20.0518,
    "lat": 41.1349,
    "areaKm2": 28337,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "012",
    "cca2": "dz",
    "cca3": "DZA",
    "name": "Algeria",
    "official": "People's Democratic Republic of Algeria",
    "capital": "Algiers",
    "capitals": [
      "Algiers"
    ],
    "lon": 2.6311,
    "lat": 28.0559,
    "areaKm2": 2322794,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "020",
    "cca2": "ad",
    "cca3": "AND",
    "name": "Andorra",
    "official": "Principality of Andorra",
    "capital": "Andorra la Vella",
    "capitals": [
      "Andorra la Vella"
    ],
    "lon": 1.5606,
    "lat": 42.542,
    "areaKm2": 441,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "024",
    "cca2": "ao",
    "cca3": "AGO",
    "name": "Angola",
    "official": "Republic of Angola",
    "capital": "Luanda",
    "capitals": [
      "Luanda"
    ],
    "lon": 17.532,
    "lat": -12.2708,
    "areaKm2": 1249384,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "028",
    "cca2": "ag",
    "cca3": "ATG",
    "name": "Antigua and Barbuda",
    "official": "Antigua and Barbuda",
    "capital": "Saint John's",
    "capitals": [
      "Saint John's"
    ],
    "lon": -61.7945,
    "lat": 17.2762,
    "areaKm2": 433,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "032",
    "cca2": "ar",
    "cca3": "ARG",
    "name": "Argentina",
    "official": "Argentine Republic",
    "capital": "Buenos Aires",
    "capitals": [
      "Buenos Aires"
    ],
    "lon": -64.7624,
    "lat": -34.6826,
    "areaKm2": 2782711,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "051",
    "cca2": "am",
    "cca3": "ARM",
    "name": "Armenia",
    "official": "Republic of Armenia",
    "capital": "Yerevan",
    "capitals": [
      "Yerevan"
    ],
    "lon": 44.9383,
    "lat": 40.2878,
    "areaKm2": 29568,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "036",
    "cca2": "au",
    "cca3": "AUS",
    "name": "Australia",
    "official": "Commonwealth of Australia",
    "capital": "Canberra",
    "capitals": [
      "Canberra"
    ],
    "lon": 134.3018,
    "lat": -25.7615,
    "areaKm2": 7706033,
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "040",
    "cca2": "at",
    "cca3": "AUT",
    "name": "Austria",
    "official": "Republic of Austria",
    "capital": "Vienna",
    "capitals": [
      "Vienna"
    ],
    "lon": 14.1103,
    "lat": 47.5923,
    "areaKm2": 83901,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "031",
    "cca2": "az",
    "cca3": "AZE",
    "name": "Azerbaijan",
    "official": "Republic of Azerbaijan",
    "capital": "Baku",
    "capitals": [
      "Baku"
    ],
    "lon": 47.548,
    "lat": 40.2866,
    "areaKm2": 86400,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "044",
    "cca2": "bs",
    "cca3": "BHS",
    "name": "Bahamas",
    "official": "Commonwealth of the Bahamas",
    "capital": "Nassau",
    "capitals": [
      "Nassau"
    ],
    "lon": -76.5909,
    "lat": 24.2793,
    "areaKm2": 12657,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "048",
    "cca2": "bh",
    "cca3": "BHR",
    "name": "Bahrain",
    "official": "Kingdom of Bahrain",
    "capital": "Manama",
    "capitals": [
      "Manama"
    ],
    "lon": 50.5425,
    "lat": 26.0417,
    "areaKm2": 544,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "050",
    "cca2": "bd",
    "cca3": "BGD",
    "name": "Bangladesh",
    "official": "People's Republic of Bangladesh",
    "capital": "Dhaka",
    "capitals": [
      "Dhaka"
    ],
    "lon": 90.2471,
    "lat": 23.861,
    "areaKm2": 135674,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "052",
    "cca2": "bb",
    "cca3": "BRB",
    "name": "Barbados",
    "official": "Barbados",
    "capital": "Bridgetown",
    "capitals": [
      "Bridgetown"
    ],
    "lon": -59.5602,
    "lat": 13.1811,
    "areaKm2": 388,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "112",
    "cca2": "by",
    "cca3": "BLR",
    "name": "Belarus",
    "official": "Republic of Belarus",
    "capital": "Minsk",
    "capitals": [
      "Minsk"
    ],
    "lon": 28.0155,
    "lat": 53.5195,
    "areaKm2": 206698,
    "region": "Europe",
    "subregion": "Eastern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "056",
    "cca2": "be",
    "cca3": "BEL",
    "name": "Belgium",
    "official": "Kingdom of Belgium",
    "capital": "Brussels",
    "capitals": [
      "Brussels"
    ],
    "lon": 4.6464,
    "lat": 50.6388,
    "areaKm2": 30627,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "084",
    "cca2": "bz",
    "cca3": "BLZ",
    "name": "Belize",
    "official": "Belize",
    "capital": "Belmopan",
    "capitals": [
      "Belmopan"
    ],
    "lon": -88.7106,
    "lat": 17.199,
    "areaKm2": 22770,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "204",
    "cca2": "bj",
    "cca3": "BEN",
    "name": "Benin",
    "official": "Republic of Benin",
    "capital": "Porto-Novo",
    "capitals": [
      "Porto-Novo"
    ],
    "lon": 2.3269,
    "lat": 9.6358,
    "areaKm2": 116553,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "064",
    "cca2": "bt",
    "cca3": "BTN",
    "name": "Bhutan",
    "official": "Kingdom of Bhutan",
    "capital": "Thimphu",
    "capitals": [
      "Thimphu"
    ],
    "lon": 90.4021,
    "lat": 27.4123,
    "areaKm2": 39870,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "068",
    "cca2": "bo",
    "cca3": "BOL",
    "name": "Bolivia",
    "official": "Plurinational State of Bolivia",
    "capital": "Sucre",
    "capitals": [
      "Sucre"
    ],
    "lon": -64.6984,
    "lat": -16.682,
    "areaKm2": 1090274,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "070",
    "cca2": "ba",
    "cca3": "BIH",
    "name": "Bosnia and Herzegovina",
    "official": "Bosnia and Herzegovina",
    "capital": "Sarajevo",
    "capitals": [
      "Sarajevo"
    ],
    "lon": 17.7748,
    "lat": 44.1714,
    "areaKm2": 51690,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "072",
    "cca2": "bw",
    "cca3": "BWA",
    "name": "Botswana",
    "official": "Republic of Botswana",
    "capital": "Gaborone",
    "capitals": [
      "Gaborone"
    ],
    "lon": 23.8085,
    "lat": -22.1655,
    "areaKm2": 580624,
    "region": "Africa",
    "subregion": "Southern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "076",
    "cca2": "br",
    "cca3": "BRA",
    "name": "Brazil",
    "official": "Federative Republic of Brazil",
    "capital": "Brasília",
    "capitals": [
      "Brasília"
    ],
    "lon": -53.2161,
    "lat": -10.64,
    "areaKm2": 8499424,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "096",
    "cca2": "bn",
    "cca3": "BRN",
    "name": "Brunei",
    "official": "Nation of Brunei, Abode of Peace",
    "capital": "Bandar Seri Begawan",
    "capitals": [
      "Bandar Seri Begawan"
    ],
    "lon": 114.7216,
    "lat": 4.5198,
    "areaKm2": 5669,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "100",
    "cca2": "bg",
    "cca3": "BGR",
    "name": "Bulgaria",
    "official": "Republic of Bulgaria",
    "capital": "Sofia",
    "capitals": [
      "Sofia"
    ],
    "lon": 25.2089,
    "lat": 42.7713,
    "areaKm2": 112424,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "854",
    "cca2": "bf",
    "cca3": "BFA",
    "name": "Burkina Faso",
    "official": "Burkina Faso",
    "capital": "Ouagadougou",
    "capitals": [
      "Ouagadougou"
    ],
    "lon": -1.7611,
    "lat": 12.2707,
    "areaKm2": 273691,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "108",
    "cca2": "bi",
    "cca3": "BDI",
    "name": "Burundi",
    "official": "Republic of Burundi",
    "capital": "Gitega",
    "capitals": [
      "Gitega"
    ],
    "lon": 29.8754,
    "lat": -3.3593,
    "areaKm2": 27217,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "116",
    "cca2": "kh",
    "cca3": "KHM",
    "name": "Cambodia",
    "official": "Kingdom of Cambodia",
    "capital": "Phnom Penh",
    "capitals": [
      "Phnom Penh"
    ],
    "lon": 104.905,
    "lat": 12.7195,
    "areaKm2": 181374,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "120",
    "cca2": "cm",
    "cca3": "CMR",
    "name": "Cameroon",
    "official": "Republic of Cameroon",
    "capital": "Yaoundé",
    "capitals": [
      "Yaoundé"
    ],
    "lon": 12.7338,
    "lat": 5.6814,
    "areaKm2": 465904,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "124",
    "cca2": "ca",
    "cca3": "CAN",
    "name": "Canada",
    "official": "Canada",
    "capital": "Ottawa",
    "capitals": [
      "Ottawa"
    ],
    "lon": -96.6026,
    "lat": 60.3811,
    "areaKm2": 9872129,
    "region": "Americas",
    "subregion": "North America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "132",
    "cca2": "cv",
    "cca3": "CPV",
    "name": "Cape Verde",
    "official": "Republic of Cabo Verde",
    "capital": "Praia",
    "capitals": [
      "Praia"
    ],
    "lon": -23.9576,
    "lat": 15.9551,
    "areaKm2": 3587,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "140",
    "cca2": "cf",
    "cca3": "CAF",
    "name": "Central African Republic",
    "official": "Central African Republic",
    "capital": "Bangui",
    "capitals": [
      "Bangui"
    ],
    "lon": 20.4617,
    "lat": 6.5723,
    "areaKm2": 620988,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "148",
    "cca2": "td",
    "cca3": "TCD",
    "name": "Chad",
    "official": "Republic of Chad",
    "capital": "N'Djamena",
    "capitals": [
      "N'Djamena"
    ],
    "lon": 18.6351,
    "lat": 15.2754,
    "areaKm2": 1270931,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "152",
    "cca2": "cl",
    "cca3": "CHL",
    "name": "Chile",
    "official": "Republic of Chile",
    "capital": "Santiago",
    "capitals": [
      "Santiago"
    ],
    "lon": -71.0473,
    "lat": -36.0505,
    "areaKm2": 737444,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "156",
    "cca2": "cn",
    "cca3": "CHN",
    "name": "China",
    "official": "People's Republic of China",
    "capital": "Beijing",
    "capitals": [
      "Beijing"
    ],
    "lon": 103.3773,
    "lat": 36.6931,
    "areaKm2": 9371251,
    "region": "Asia",
    "subregion": "Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "170",
    "cca2": "co",
    "cca3": "COL",
    "name": "Colombia",
    "official": "Republic of Colombia",
    "capital": "Bogotá",
    "capitals": [
      "Bogotá"
    ],
    "lon": -73.077,
    "lat": 3.9034,
    "areaKm2": 1139437,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "174",
    "cca2": "km",
    "cca3": "COM",
    "name": "Comoros",
    "official": "Union of the Comoros",
    "capital": "Moroni",
    "capitals": [
      "Moroni"
    ],
    "lon": 43.6844,
    "lat": -11.879,
    "areaKm2": 1582,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "188",
    "cca2": "cr",
    "cca3": "CRI",
    "name": "Costa Rica",
    "official": "Republic of Costa Rica",
    "capital": "San José",
    "capitals": [
      "San José"
    ],
    "lon": -84.1901,
    "lat": 9.9764,
    "areaKm2": 51511,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "191",
    "cca2": "hr",
    "cca3": "HRV",
    "name": "Croatia",
    "official": "Republic of Croatia",
    "capital": "Zagreb",
    "capitals": [
      "Zagreb"
    ],
    "lon": 16.401,
    "lat": 45.0758,
    "areaKm2": 54414,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "192",
    "cca2": "cu",
    "cca3": "CUB",
    "name": "Cuba",
    "official": "Republic of Cuba",
    "capital": "Havana",
    "capitals": [
      "Havana"
    ],
    "lon": -78.987,
    "lat": 21.638,
    "areaKm2": 109285,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "196",
    "cca2": "cy",
    "cca3": "CYP",
    "name": "Cyprus",
    "official": "Republic of Cyprus",
    "capital": "Nicosia",
    "capitals": [
      "Nicosia"
    ],
    "lon": 33.0056,
    "lat": 34.9172,
    "areaKm2": 5710,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "203",
    "cca2": "cz",
    "cca3": "CZE",
    "name": "Czechia",
    "official": "Czech Republic",
    "capital": "Prague",
    "capitals": [
      "Prague"
    ],
    "lon": 15.3195,
    "lat": 49.738,
    "areaKm2": 78487,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "208",
    "cca2": "dk",
    "cca3": "DNK",
    "name": "Denmark",
    "official": "Kingdom of Denmark",
    "capital": "Copenhagen",
    "capitals": [
      "Copenhagen"
    ],
    "lon": 10.0424,
    "lat": 55.9751,
    "areaKm2": 42411,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "262",
    "cca2": "dj",
    "cca3": "DJI",
    "name": "Djibouti",
    "official": "Republic of Djibouti",
    "capital": "Djibouti",
    "capitals": [
      "Djibouti"
    ],
    "lon": 42.56,
    "lat": 11.7488,
    "areaKm2": 21693,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "212",
    "cca2": "dm",
    "cca3": "DMA",
    "name": "Dominica",
    "official": "Commonwealth of Dominica",
    "capital": "Roseau",
    "capitals": [
      "Roseau"
    ],
    "lon": -61.3576,
    "lat": 15.4394,
    "areaKm2": 688,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "214",
    "cca2": "do",
    "cca3": "DOM",
    "name": "Dominican Republic",
    "official": "Dominican Republic",
    "capital": "Santo Domingo",
    "capitals": [
      "Santo Domingo"
    ],
    "lon": -70.5052,
    "lat": 18.8951,
    "areaKm2": 48592,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "180",
    "cca2": "cd",
    "cca3": "COD",
    "name": "DR Congo",
    "official": "Democratic Republic of the Congo",
    "capital": "Kinshasa",
    "capitals": [
      "Kinshasa"
    ],
    "lon": 23.6378,
    "lat": -2.8654,
    "areaKm2": 2334709,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "218",
    "cca2": "ec",
    "cca3": "ECU",
    "name": "Ecuador",
    "official": "Republic of Ecuador",
    "capital": "Quito",
    "capitals": [
      "Quito"
    ],
    "lon": -78.7491,
    "lat": -1.4243,
    "areaKm2": 255659,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "818",
    "cca2": "eg",
    "cca3": "EGY",
    "name": "Egypt",
    "official": "Arab Republic of Egypt",
    "capital": "Cairo",
    "capitals": [
      "Cairo"
    ],
    "lon": 29.8779,
    "lat": 26.4596,
    "areaKm2": 1003710,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "222",
    "cca2": "sv",
    "cca3": "SLV",
    "name": "El Salvador",
    "official": "Republic of El Salvador",
    "capital": "San Salvador",
    "capitals": [
      "San Salvador"
    ],
    "lon": -88.8713,
    "lat": 13.7396,
    "areaKm2": 20401,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "226",
    "cca2": "gq",
    "cca3": "GNQ",
    "name": "Equatorial Guinea",
    "official": "Republic of Equatorial Guinea",
    "capital": "Malabo",
    "capitals": [
      "Malabo"
    ],
    "lon": 10.3415,
    "lat": 1.7057,
    "areaKm2": 26637,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "232",
    "cca2": "er",
    "cca3": "ERI",
    "name": "Eritrea",
    "official": "State of Eritrea",
    "capital": "Asmara",
    "capitals": [
      "Asmara"
    ],
    "lon": 38.8571,
    "lat": 15.361,
    "areaKm2": 123678,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "233",
    "cca2": "ee",
    "cca3": "EST",
    "name": "Estonia",
    "official": "Republic of Estonia",
    "capital": "Tallinn",
    "capitals": [
      "Tallinn"
    ],
    "lon": 25.5453,
    "lat": 58.6727,
    "areaKm2": 45442,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "748",
    "cca2": "sz",
    "cca3": "SWZ",
    "name": "Eswatini",
    "official": "Kingdom of Eswatini",
    "capital": "Lobamba",
    "capitals": [
      "Lobamba"
    ],
    "lon": 31.4816,
    "lat": -26.5578,
    "areaKm2": 17007,
    "region": "Africa",
    "subregion": "Southern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "231",
    "cca2": "et",
    "cca3": "ETH",
    "name": "Ethiopia",
    "official": "Federal Democratic Republic of Ethiopia",
    "capital": "Addis Ababa",
    "capitals": [
      "Addis Ababa"
    ],
    "lon": 39.6097,
    "lat": 8.6144,
    "areaKm2": 1131764,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "242",
    "cca2": "fj",
    "cca3": "FJI",
    "name": "Fiji",
    "official": "Republic of Fiji",
    "capital": "Suva",
    "capitals": [
      "Suva"
    ],
    "lon": 178.5121,
    "lat": -17.4278,
    "areaKm2": 18398,
    "region": "Oceania",
    "subregion": "Melanesia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "246",
    "cca2": "fi",
    "cca3": "FIN",
    "name": "Finland",
    "official": "Republic of Finland",
    "capital": "Helsinki",
    "capitals": [
      "Helsinki"
    ],
    "lon": 26.195,
    "lat": 64.2552,
    "areaKm2": 330483,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "250",
    "cca2": "fr",
    "cca3": "FRA",
    "name": "France",
    "official": "French Republic",
    "capital": "Paris",
    "capitals": [
      "Paris"
    ],
    "lon": 2.5727,
    "lat": 46.5057,
    "areaKm2": 635066,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "266",
    "cca2": "ga",
    "cca3": "GAB",
    "name": "Gabon",
    "official": "Gabonese Republic",
    "capital": "Libreville",
    "capitals": [
      "Libreville"
    ],
    "lon": 11.7885,
    "lat": -0.5865,
    "areaKm2": 260716,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "270",
    "cca2": "gm",
    "cca3": "GMB",
    "name": "Gambia",
    "official": "Republic of the Gambia",
    "capital": "Banjul",
    "capitals": [
      "Banjul"
    ],
    "lon": -15.3959,
    "lat": 13.451,
    "areaKm2": 10324,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "268",
    "cca2": "ge",
    "cca3": "GEO",
    "name": "Georgia",
    "official": "Georgia",
    "capital": "Tbilisi",
    "capitals": [
      "Tbilisi"
    ],
    "lon": 43.5242,
    "lat": 42.1731,
    "areaKm2": 69298,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "276",
    "cca2": "de",
    "cca3": "DEU",
    "name": "Germany",
    "official": "Federal Republic of Germany",
    "capital": "Berlin",
    "capitals": [
      "Berlin"
    ],
    "lon": 10.3644,
    "lat": 51.0506,
    "areaKm2": 356164,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "288",
    "cca2": "gh",
    "cca3": "GHA",
    "name": "Ghana",
    "official": "Republic of Ghana",
    "capital": "Accra",
    "capitals": [
      "Accra"
    ],
    "lon": -1.217,
    "lat": 7.9476,
    "areaKm2": 239590,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "300",
    "cca2": "gr",
    "cca3": "GRC",
    "name": "Greece",
    "official": "Hellenic Republic",
    "capital": "Athens",
    "capitals": [
      "Athens"
    ],
    "lon": 22.9644,
    "lat": 39.048,
    "areaKm2": 130177,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "308",
    "cca2": "gd",
    "cca3": "GRD",
    "name": "Grenada",
    "official": "Grenada",
    "capital": "St. George's",
    "capitals": [
      "St. George's"
    ],
    "lon": -61.6818,
    "lat": 12.1174,
    "areaKm2": 288,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "320",
    "cca2": "gt",
    "cca3": "GTM",
    "name": "Guatemala",
    "official": "Republic of Guatemala",
    "capital": "Guatemala City",
    "capitals": [
      "Guatemala City"
    ],
    "lon": -90.3674,
    "lat": 15.6901,
    "areaKm2": 108520,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "324",
    "cca2": "gn",
    "cca3": "GIN",
    "name": "Guinea",
    "official": "Republic of Guinea",
    "capital": "Conakry",
    "capitals": [
      "Conakry"
    ],
    "lon": -10.9345,
    "lat": 10.4374,
    "areaKm2": 244938,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "624",
    "cca2": "gw",
    "cca3": "GNB",
    "name": "Guinea-Bissau",
    "official": "Republic of Guinea-Bissau",
    "capital": "Bissau",
    "capitals": [
      "Bissau"
    ],
    "lon": -14.9499,
    "lat": 12.0483,
    "areaKm2": 32044,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "328",
    "cca2": "gy",
    "cca3": "GUY",
    "name": "Guyana",
    "official": "Co-operative Republic of Guyana",
    "capital": "Georgetown",
    "capitals": [
      "Georgetown"
    ],
    "lon": -58.9797,
    "lat": 4.7896,
    "areaKm2": 211931,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "332",
    "cca2": "ht",
    "cca3": "HTI",
    "name": "Haiti",
    "official": "Republic of Haiti",
    "capital": "Port-au-Prince",
    "capitals": [
      "Port-au-Prince"
    ],
    "lon": -72.687,
    "lat": 18.9346,
    "areaKm2": 26822,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "340",
    "cca2": "hn",
    "cca3": "HND",
    "name": "Honduras",
    "official": "Republic of Honduras",
    "capital": "Tegucigalpa",
    "capitals": [
      "Tegucigalpa"
    ],
    "lon": -86.6178,
    "lat": 14.829,
    "areaKm2": 113532,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "348",
    "cca2": "hu",
    "cca3": "HUN",
    "name": "Hungary",
    "official": "Hungary",
    "capital": "Budapest",
    "capitals": [
      "Budapest"
    ],
    "lon": 19.3793,
    "lat": 47.1659,
    "areaKm2": 92966,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "352",
    "cca2": "is",
    "cca3": "ISL",
    "name": "Iceland",
    "official": "Iceland",
    "capital": "Reykjavik",
    "capitals": [
      "Reykjavik"
    ],
    "lon": -18.5801,
    "lat": 64.9979,
    "areaKm2": 101161,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "356",
    "cca2": "in",
    "cca3": "IND",
    "name": "India",
    "official": "Republic of India",
    "capital": "New Delhi",
    "capitals": [
      "New Delhi"
    ],
    "lon": 79.5635,
    "lat": 22.7768,
    "areaKm2": 3155816,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "360",
    "cca2": "id",
    "cca3": "IDN",
    "name": "Indonesia",
    "official": "Republic of Indonesia",
    "capital": "Jakarta",
    "capitals": [
      "Jakarta"
    ],
    "lon": 117.1778,
    "lat": -2.2635,
    "areaKm2": 1872247,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "364",
    "cca2": "ir",
    "cca3": "IRN",
    "name": "Iran",
    "official": "Islamic Republic of Iran",
    "capital": "Tehran",
    "capitals": [
      "Tehran"
    ],
    "lon": 54.4408,
    "lat": 32.5273,
    "areaKm2": 1622852,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "368",
    "cca2": "iq",
    "cca3": "IRQ",
    "name": "Iraq",
    "official": "Republic of Iraq",
    "capital": "Baghdad",
    "capitals": [
      "Baghdad"
    ],
    "lon": 43.7737,
    "lat": 33.0096,
    "areaKm2": 437463,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "372",
    "cca2": "ie",
    "cca3": "IRL",
    "name": "Ireland",
    "official": "Republic of Ireland",
    "capital": "Dublin",
    "capitals": [
      "Dublin"
    ],
    "lon": -8.1459,
    "lat": 53.1623,
    "areaKm2": 68700,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "376",
    "cca2": "il",
    "cca3": "ISR",
    "name": "Israel",
    "official": "State of Israel",
    "capital": "Jerusalem",
    "capitals": [
      "Jerusalem"
    ],
    "lon": 34.9997,
    "lat": 31.4516,
    "areaKm2": 22284,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "380",
    "cca2": "it",
    "cca3": "ITA",
    "name": "Italy",
    "official": "Italian Republic",
    "capital": "Rome",
    "capitals": [
      "Rome"
    ],
    "lon": 12.2008,
    "lat": 42.7168,
    "areaKm2": 300268,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "384",
    "cca2": "ci",
    "cca3": "CIV",
    "name": "Ivory Coast",
    "official": "Republic of Côte d'Ivoire",
    "capital": "Yamoussoukro",
    "capitals": [
      "Yamoussoukro"
    ],
    "lon": -5.5691,
    "lat": 7.6257,
    "areaKm2": 322299,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "388",
    "cca2": "jm",
    "cca3": "JAM",
    "name": "Jamaica",
    "official": "Jamaica",
    "capital": "Kingston",
    "capitals": [
      "Kingston"
    ],
    "lon": -77.3145,
    "lat": 18.1571,
    "areaKm2": 10935,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "392",
    "cca2": "jp",
    "cca3": "JPN",
    "name": "Japan",
    "official": "Japan",
    "capital": "Tokyo",
    "capitals": [
      "Tokyo"
    ],
    "lon": 137.6607,
    "lat": 37.4607,
    "areaKm2": 370075,
    "region": "Asia",
    "subregion": "Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "400",
    "cca2": "jo",
    "cca3": "JOR",
    "name": "Jordan",
    "official": "Hashemite Kingdom of Jordan",
    "capital": "Amman",
    "capitals": [
      "Amman"
    ],
    "lon": 36.7575,
    "lat": 31.2385,
    "areaKm2": 88856,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "398",
    "cca2": "kz",
    "cca3": "KAZ",
    "name": "Kazakhstan",
    "official": "Republic of Kazakhstan",
    "capital": "Astana",
    "capitals": [
      "Astana"
    ],
    "lon": 67.2456,
    "lat": 48.3617,
    "areaKm2": 2712754,
    "region": "Asia",
    "subregion": "Central Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "404",
    "cca2": "ke",
    "cca3": "KEN",
    "name": "Kenya",
    "official": "Republic of Kenya",
    "capital": "Nairobi",
    "capitals": [
      "Nairobi"
    ],
    "lon": 37.7964,
    "lat": 0.5995,
    "areaKm2": 594850,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "296",
    "cca2": "ki",
    "cca3": "KIR",
    "name": "Kiribati",
    "official": "Independent and Sovereign Republic of Kiribati",
    "capital": "South Tarawa",
    "capitals": [
      "South Tarawa"
    ],
    "lon": -158.384,
    "lat": 0.9277,
    "areaKm2": 941,
    "region": "Oceania",
    "subregion": "Micronesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "414",
    "cca2": "kw",
    "cca3": "KWT",
    "name": "Kuwait",
    "official": "State of Kuwait",
    "capital": "Kuwait City",
    "capitals": [
      "Kuwait City"
    ],
    "lon": 47.5882,
    "lat": 29.3333,
    "areaKm2": 17330,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "417",
    "cca2": "kg",
    "cca3": "KGZ",
    "name": "Kyrgyzstan",
    "official": "Kyrgyz Republic",
    "capital": "Bishkek",
    "capitals": [
      "Bishkek"
    ],
    "lon": 74.5092,
    "lat": 41.4744,
    "areaKm2": 198662,
    "region": "Asia",
    "subregion": "Central Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "418",
    "cca2": "la",
    "cca3": "LAO",
    "name": "Laos",
    "official": "Lao People's Democratic Republic",
    "capital": "Vientiane",
    "capitals": [
      "Vientiane"
    ],
    "lon": 103.7752,
    "lat": 18.4872,
    "areaKm2": 228929,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "428",
    "cca2": "lv",
    "cca3": "LVA",
    "name": "Latvia",
    "official": "Republic of Latvia",
    "capital": "Riga",
    "capitals": [
      "Riga"
    ],
    "lon": 24.9203,
    "lat": 56.8596,
    "areaKm2": 64254,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "422",
    "cca2": "lb",
    "cca3": "LBN",
    "name": "Lebanon",
    "official": "Lebanese Republic",
    "capital": "Beirut",
    "capitals": [
      "Beirut"
    ],
    "lon": 35.878,
    "lat": 33.9212,
    "areaKm2": 10010,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "426",
    "cca2": "ls",
    "cca3": "LSO",
    "name": "Lesotho",
    "official": "Kingdom of Lesotho",
    "capital": "Maseru",
    "capitals": [
      "Maseru"
    ],
    "lon": 28.229,
    "lat": -29.5791,
    "areaKm2": 30020,
    "region": "Africa",
    "subregion": "Southern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "430",
    "cca2": "lr",
    "cca3": "LBR",
    "name": "Liberia",
    "official": "Republic of Liberia",
    "capital": "Monrovia",
    "capitals": [
      "Monrovia"
    ],
    "lon": -9.3198,
    "lat": 6.4522,
    "areaKm2": 95648,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "434",
    "cca2": "ly",
    "cca3": "LBY",
    "name": "Libya",
    "official": "State of Libya",
    "capital": "Tripoli",
    "capitals": [
      "Tripoli"
    ],
    "lon": 18.0662,
    "lat": 27.0168,
    "areaKm2": 1626374,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "438",
    "cca2": "li",
    "cca3": "LIE",
    "name": "Liechtenstein",
    "official": "Principality of Liechtenstein",
    "capital": "Vaduz",
    "capitals": [
      "Vaduz"
    ],
    "lon": 9.5357,
    "lat": 47.1367,
    "areaKm2": 138,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "440",
    "cca2": "lt",
    "cca3": "LTU",
    "name": "Lithuania",
    "official": "Republic of Lithuania",
    "capital": "Vilnius",
    "capitals": [
      "Vilnius"
    ],
    "lon": 23.8972,
    "lat": 55.3237,
    "areaKm2": 64519,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "442",
    "cca2": "lu",
    "cca3": "LUX",
    "name": "Luxembourg",
    "official": "Grand Duchy of Luxembourg",
    "capital": "Luxembourg",
    "capitals": [
      "Luxembourg"
    ],
    "lon": 6.0722,
    "lat": 49.7669,
    "areaKm2": 2614,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "450",
    "cca2": "mg",
    "cca3": "MDG",
    "name": "Madagascar",
    "official": "Republic of Madagascar",
    "capital": "Antananarivo",
    "capitals": [
      "Antananarivo"
    ],
    "lon": 46.7429,
    "lat": -19.3166,
    "areaKm2": 594623,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "454",
    "cca2": "mw",
    "cca3": "MWI",
    "name": "Malawi",
    "official": "Republic of Malawi",
    "capital": "Lilongwe",
    "capitals": [
      "Lilongwe"
    ],
    "lon": 34.2825,
    "lat": -13.2042,
    "areaKm2": 119763,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "458",
    "cca2": "my",
    "cca3": "MYS",
    "name": "Malaysia",
    "official": "Malaysia",
    "capital": "Kuala Lumpur",
    "capitals": [
      "Kuala Lumpur"
    ],
    "lon": 109.7021,
    "lat": 3.811,
    "areaKm2": 327622,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "462",
    "cca2": "mv",
    "cca3": "MDV",
    "name": "Maldives",
    "official": "Republic of the Maldives",
    "capital": "Malé",
    "capitals": [
      "Malé"
    ],
    "lon": 73.4573,
    "lat": 3.7316,
    "areaKm2": 67,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "466",
    "cca2": "ml",
    "cca3": "MLI",
    "name": "Mali",
    "official": "Republic of Mali",
    "capital": "Bamako",
    "capitals": [
      "Bamako"
    ],
    "lon": -3.5905,
    "lat": 17.3151,
    "areaKm2": 1258188,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "470",
    "cca2": "mt",
    "cca3": "MLT",
    "name": "Malta",
    "official": "Republic of Malta",
    "capital": "Valletta",
    "capitals": [
      "Valletta"
    ],
    "lon": 14.405,
    "lat": 35.9215,
    "areaKm2": 276,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "584",
    "cca2": "mh",
    "cca3": "MHL",
    "name": "Marshall Islands",
    "official": "Republic of the Marshall Islands",
    "capital": "Majuro",
    "capitals": [
      "Majuro"
    ],
    "lon": 170.3313,
    "lat": 7.015,
    "areaKm2": 236,
    "region": "Oceania",
    "subregion": "Micronesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "478",
    "cca2": "mr",
    "cca3": "MRT",
    "name": "Mauritania",
    "official": "Islamic Republic of Mauritania",
    "capital": "Nouakchott",
    "capitals": [
      "Nouakchott"
    ],
    "lon": -10.37,
    "lat": 20.2203,
    "areaKm2": 1038355,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "480",
    "cca2": "mu",
    "cca3": "MUS",
    "name": "Mauritius",
    "official": "Republic of Mauritius",
    "capital": "Port Louis",
    "capitals": [
      "Port Louis"
    ],
    "lon": 57.5714,
    "lat": -20.2779,
    "areaKm2": 1880,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "484",
    "cca2": "mx",
    "cca3": "MEX",
    "name": "Mexico",
    "official": "United Mexican States",
    "capital": "Mexico City",
    "capitals": [
      "Mexico City"
    ],
    "lon": -102.171,
    "lat": 23.9242,
    "areaKm2": 1962284,
    "region": "Americas",
    "subregion": "North America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "583",
    "cca2": "fm",
    "cca3": "FSM",
    "name": "Micronesia",
    "official": "Federated States of Micronesia",
    "capital": "Palikir",
    "capitals": [
      "Palikir"
    ],
    "lon": 153.2966,
    "lat": 7.5361,
    "areaKm2": 524,
    "region": "Oceania",
    "subregion": "Micronesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "498",
    "cca2": "md",
    "cca3": "MDA",
    "name": "Moldova",
    "official": "Republic of Moldova",
    "capital": "Chișinău",
    "capitals": [
      "Chișinău"
    ],
    "lon": 28.4661,
    "lat": 47.187,
    "areaKm2": 33115,
    "region": "Europe",
    "subregion": "Eastern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "492",
    "cca2": "mc",
    "cca3": "MCO",
    "name": "Monaco",
    "official": "Principality of Monaco",
    "capital": "Monaco",
    "capitals": [
      "Monaco"
    ],
    "lon": 7.4073,
    "lat": 43.7526,
    "areaKm2": 12,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "496",
    "cca2": "mn",
    "cca3": "MNG",
    "name": "Mongolia",
    "official": "Mongolia",
    "capital": "Ulan Bator",
    "capitals": [
      "Ulan Bator"
    ],
    "lon": 103.1241,
    "lat": 46.9562,
    "areaKm2": 1560432,
    "region": "Asia",
    "subregion": "Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "499",
    "cca2": "me",
    "cca3": "MNE",
    "name": "Montenegro",
    "official": "Montenegro",
    "capital": "Podgorica",
    "capitals": [
      "Podgorica"
    ],
    "lon": 19.2387,
    "lat": 42.7879,
    "areaKm2": 13663,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "504",
    "cca2": "ma",
    "cca3": "MAR",
    "name": "Morocco",
    "official": "Kingdom of Morocco",
    "capital": "Rabat",
    "capitals": [
      "Rabat"
    ],
    "lon": -8.7281,
    "lat": 29.7666,
    "areaKm2": 582379,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "508",
    "cca2": "mz",
    "cca3": "MOZ",
    "name": "Mozambique",
    "official": "Republic of Mozambique",
    "capital": "Maputo",
    "capitals": [
      "Maputo"
    ],
    "lon": 35.6028,
    "lat": -17.1956,
    "areaKm2": 790645,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "104",
    "cca2": "mm",
    "cca3": "MMR",
    "name": "Myanmar",
    "official": "Republic of the Union of Myanmar",
    "capital": "Naypyidaw",
    "capitals": [
      "Naypyidaw"
    ],
    "lon": 96.4948,
    "lat": 21.1131,
    "areaKm2": 662748,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "516",
    "cca2": "na",
    "cca3": "NAM",
    "name": "Namibia",
    "official": "Republic of Namibia",
    "capital": "Windhoek",
    "capitals": [
      "Windhoek"
    ],
    "lon": 17.1952,
    "lat": -22.0697,
    "areaKm2": 824753,
    "region": "Africa",
    "subregion": "Southern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "520",
    "cca2": "nr",
    "cca3": "NRU",
    "name": "Nauru",
    "official": "Republic of Nauru",
    "capital": "Yaren",
    "capitals": [
      "Yaren"
    ],
    "lon": 166.9326,
    "lat": -0.5189,
    "areaKm2": 28,
    "region": "Oceania",
    "subregion": "Micronesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "524",
    "cca2": "np",
    "cca3": "NPL",
    "name": "Nepal",
    "official": "Federal Democratic Republic of Nepal",
    "capital": "Kathmandu",
    "capitals": [
      "Kathmandu"
    ],
    "lon": 83.9473,
    "lat": 28.2579,
    "areaKm2": 147193,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "528",
    "cca2": "nl",
    "cca3": "NLD",
    "name": "Netherlands",
    "official": "Kingdom of the Netherlands",
    "capital": "Amsterdam",
    "capitals": [
      "Amsterdam"
    ],
    "lon": 5.58,
    "lat": 52.2618,
    "areaKm2": 37132,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "554",
    "cca2": "nz",
    "cca3": "NZL",
    "name": "New Zealand",
    "official": "New Zealand",
    "capital": "Wellington",
    "capitals": [
      "Wellington"
    ],
    "lon": 172.9211,
    "lat": -41.7028,
    "areaKm2": 266829,
    "region": "Oceania",
    "subregion": "Australia and New Zealand",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "558",
    "cca2": "ni",
    "cca3": "NIC",
    "name": "Nicaragua",
    "official": "Republic of Nicaragua",
    "capital": "Managua",
    "capitals": [
      "Managua"
    ],
    "lon": -85.0319,
    "lat": 12.845,
    "areaKm2": 129225,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "562",
    "cca2": "ne",
    "cca3": "NER",
    "name": "Niger",
    "official": "Republic of Niger",
    "capital": "Niamey",
    "capitals": [
      "Niamey"
    ],
    "lon": 9.3317,
    "lat": 17.4119,
    "areaKm2": 1185114,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "566",
    "cca2": "ng",
    "cca3": "NGA",
    "name": "Nigeria",
    "official": "Federal Republic of Nigeria",
    "capital": "Abuja",
    "capitals": [
      "Abuja"
    ],
    "lon": 8.0797,
    "lat": 9.591,
    "areaKm2": 911499,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "408",
    "cca2": "kp",
    "cca3": "PRK",
    "name": "North Korea",
    "official": "Democratic People's Republic of Korea",
    "capital": "Pyongyang",
    "capitals": [
      "Pyongyang"
    ],
    "lon": 127.159,
    "lat": 40.1401,
    "areaKm2": 122497,
    "region": "Asia",
    "subregion": "Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "807",
    "cca2": "mk",
    "cca3": "MKD",
    "name": "North Macedonia",
    "official": "Republic of North Macedonia",
    "capital": "Skopje",
    "capitals": [
      "Skopje"
    ],
    "lon": 21.6807,
    "lat": 41.5953,
    "areaKm2": 25366,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "578",
    "cca2": "no",
    "cca3": "NOR",
    "name": "Norway",
    "official": "Kingdom of Norway",
    "capital": "Oslo",
    "capitals": [
      "Oslo"
    ],
    "lon": 12.7445,
    "lat": 66.3538,
    "areaKm2": 384265,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "512",
    "cca2": "om",
    "cca3": "OMN",
    "name": "Oman",
    "official": "Sultanate of Oman",
    "capital": "Muscat",
    "capitals": [
      "Muscat"
    ],
    "lon": 56.0622,
    "lat": 20.586,
    "areaKm2": 312042,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "586",
    "cca2": "pk",
    "cca3": "PAK",
    "name": "Pakistan",
    "official": "Islamic Republic of Pakistan",
    "capital": "Islamabad",
    "capitals": [
      "Islamabad"
    ],
    "lon": 69.1684,
    "lat": 29.884,
    "areaKm2": 873774,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "585",
    "cca2": "pw",
    "cca3": "PLW",
    "name": "Palau",
    "official": "Republic of Palau",
    "capital": "Ngerulmud",
    "capitals": [
      "Ngerulmud"
    ],
    "lon": 134.4056,
    "lat": 7.286,
    "areaKm2": 343,
    "region": "Oceania",
    "subregion": "Micronesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "275",
    "cca2": "ps",
    "cca3": "PSE",
    "name": "Palestine",
    "official": "State of Palestine",
    "capital": "Ramallah",
    "capitals": [
      "Ramallah"
    ],
    "lon": 35.1952,
    "lat": 31.915,
    "areaKm2": 6336,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "591",
    "cca2": "pa",
    "cca3": "PAN",
    "name": "Panama",
    "official": "Republic of Panama",
    "capital": "Panama City",
    "capitals": [
      "Panama City"
    ],
    "lon": -80.1192,
    "lat": 8.5204,
    "areaKm2": 74235,
    "region": "Americas",
    "subregion": "Central America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "598",
    "cca2": "pg",
    "cca3": "PNG",
    "name": "Papua New Guinea",
    "official": "Independent State of Papua New Guinea",
    "capital": "Port Moresby",
    "capitals": [
      "Port Moresby"
    ],
    "lon": 145.2,
    "lat": -6.4688,
    "areaKm2": 464273,
    "region": "Oceania",
    "subregion": "Melanesia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "600",
    "cca2": "py",
    "cca3": "PRY",
    "name": "Paraguay",
    "official": "Republic of Paraguay",
    "capital": "Asunción",
    "capitals": [
      "Asunción"
    ],
    "lon": -58.4433,
    "lat": -23.2089,
    "areaKm2": 400901,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "604",
    "cca2": "pe",
    "cca3": "PER",
    "name": "Peru",
    "official": "Republic of Peru",
    "capital": "Lima",
    "capitals": [
      "Lima"
    ],
    "lon": -74.4208,
    "lat": -9.1071,
    "areaKm2": 1296283,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "608",
    "cca2": "ph",
    "cca3": "PHL",
    "name": "Philippines",
    "official": "Republic of the Philippines",
    "capital": "Manila",
    "capitals": [
      "Manila"
    ],
    "lon": 122.9192,
    "lat": 11.7289,
    "areaKm2": 290319,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "616",
    "cca2": "pl",
    "cca3": "POL",
    "name": "Poland",
    "official": "Republic of Poland",
    "capital": "Warsaw",
    "capitals": [
      "Warsaw"
    ],
    "lon": 19.4198,
    "lat": 52.1119,
    "areaKm2": 312567,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "620",
    "cca2": "pt",
    "cca3": "PRT",
    "name": "Portugal",
    "official": "Portuguese Republic",
    "capital": "Lisbon",
    "capitals": [
      "Lisbon"
    ],
    "lon": -8.529,
    "lat": 39.6064,
    "areaKm2": 90766,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "634",
    "cca2": "qa",
    "cca3": "QAT",
    "name": "Qatar",
    "official": "State of Qatar",
    "capital": "Doha",
    "capitals": [
      "Doha"
    ],
    "lon": 51.1844,
    "lat": 25.3048,
    "areaKm2": 11076,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "178",
    "cca2": "cg",
    "cca3": "COG",
    "name": "Republic of the Congo",
    "official": "Republic of the Congo",
    "capital": "Brazzaville",
    "capitals": [
      "Brazzaville"
    ],
    "lon": 15.2212,
    "lat": -0.8371,
    "areaKm2": 346858,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "642",
    "cca2": "ro",
    "cca3": "ROU",
    "name": "Romania",
    "official": "Romania",
    "capital": "Bucharest",
    "capitals": [
      "Bucharest"
    ],
    "lon": 24.983,
    "lat": 45.8486,
    "areaKm2": 235753,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "643",
    "cca2": "ru",
    "cca3": "RUS",
    "name": "Russia",
    "official": "Russian Federation",
    "capital": "Moscow",
    "capitals": [
      "Moscow"
    ],
    "lon": 95.4581,
    "lat": 66.0305,
    "areaKm2": 16879748,
    "region": "Europe",
    "subregion": "Eastern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "646",
    "cca2": "rw",
    "cca3": "RWA",
    "name": "Rwanda",
    "official": "Republic of Rwanda",
    "capital": "Kigali",
    "capitals": [
      "Kigali"
    ],
    "lon": 29.9199,
    "lat": -1.9903,
    "areaKm2": 25377,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "659",
    "cca2": "kn",
    "cca3": "KNA",
    "name": "Saint Kitts and Nevis",
    "official": "Federation of Saint Christopher and Nevis",
    "capital": "Basseterre",
    "capitals": [
      "Basseterre"
    ],
    "lon": -62.6873,
    "lat": 17.2647,
    "areaKm2": 234,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "662",
    "cca2": "lc",
    "cca3": "LCA",
    "name": "Saint Lucia",
    "official": "Saint Lucia",
    "capital": "Castries",
    "capitals": [
      "Castries"
    ],
    "lon": -60.9696,
    "lat": 13.8946,
    "areaKm2": 552,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "670",
    "cca2": "vc",
    "cca3": "VCT",
    "name": "Saint Vincent and the Grenadines",
    "official": "Saint Vincent and the Grenadines",
    "capital": "Kingstown",
    "capitals": [
      "Kingstown"
    ],
    "lon": -61.2008,
    "lat": 13.2251,
    "areaKm2": 312,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "882",
    "cca2": "ws",
    "cca3": "WSM",
    "name": "Samoa",
    "official": "Independent State of Samoa",
    "capital": "Apia",
    "capitals": [
      "Apia"
    ],
    "lon": -172.1649,
    "lat": -13.7536,
    "areaKm2": 2705,
    "region": "Oceania",
    "subregion": "Polynesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "674",
    "cca2": "sm",
    "cca3": "SMR",
    "name": "San Marino",
    "official": "Most Serene Republic of San Marino",
    "capital": "City of San Marino",
    "capitals": [
      "City of San Marino"
    ],
    "lon": 12.4594,
    "lat": 43.9415,
    "areaKm2": 70,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "678",
    "cca2": "st",
    "cca3": "STP",
    "name": "São Tomé and Príncipe",
    "official": "Democratic Republic of São Tomé and Príncipe",
    "capital": "São Tomé",
    "capitals": [
      "São Tomé"
    ],
    "lon": 6.7235,
    "lat": 0.4434,
    "areaKm2": 979,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "682",
    "cca2": "sa",
    "cca3": "SAU",
    "name": "Saudi Arabia",
    "official": "Kingdom of Saudi Arabia",
    "capital": "Riyadh",
    "capitals": [
      "Riyadh"
    ],
    "lon": 44.6632,
    "lat": 24.0865,
    "areaKm2": 1925876,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "686",
    "cca2": "sn",
    "cca3": "SEN",
    "name": "Senegal",
    "official": "Republic of Senegal",
    "capital": "Dakar",
    "capitals": [
      "Dakar"
    ],
    "lon": -14.4691,
    "lat": 14.3648,
    "areaKm2": 197300,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "688",
    "cca2": "rs",
    "cca3": "SRB",
    "name": "Serbia",
    "official": "Republic of Serbia",
    "capital": "Belgrade",
    "capitals": [
      "Belgrade"
    ],
    "lon": 20.8064,
    "lat": 44.2114,
    "areaKm2": 77482,
    "region": "Europe",
    "subregion": "Southeast Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "690",
    "cca2": "sc",
    "cca3": "SYC",
    "name": "Seychelles",
    "official": "Republic of Seychelles",
    "capital": "Victoria",
    "capitals": [
      "Victoria"
    ],
    "lon": 55.476,
    "lat": -4.6601,
    "areaKm2": 172,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "694",
    "cca2": "sl",
    "cca3": "SLE",
    "name": "Sierra Leone",
    "official": "Republic of Sierra Leone",
    "capital": "Freetown",
    "capitals": [
      "Freetown"
    ],
    "lon": -11.7927,
    "lat": 8.5625,
    "areaKm2": 71877,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "702",
    "cca2": "sg",
    "cca3": "SGP",
    "name": "Singapore",
    "official": "Republic of Singapore",
    "capital": "Singapore",
    "capitals": [
      "Singapore"
    ],
    "lon": 103.817,
    "lat": 1.359,
    "areaKm2": 484,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "703",
    "cca2": "sk",
    "cca3": "SVK",
    "name": "Slovakia",
    "official": "Slovak Republic",
    "capital": "Bratislava",
    "capitals": [
      "Bratislava"
    ],
    "lon": 19.4692,
    "lat": 48.7113,
    "areaKm2": 48338,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "705",
    "cca2": "si",
    "cca3": "SVN",
    "name": "Slovenia",
    "official": "Republic of Slovenia",
    "capital": "Ljubljana",
    "capitals": [
      "Ljubljana"
    ],
    "lon": 14.8009,
    "lat": 46.1161,
    "areaKm2": 20198,
    "region": "Europe",
    "subregion": "Central Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "090",
    "cca2": "sb",
    "cca3": "SLB",
    "name": "Solomon Islands",
    "official": "Solomon Islands",
    "capital": "Honiara",
    "capitals": [
      "Honiara"
    ],
    "lon": 159.6202,
    "lat": -8.922,
    "areaKm2": 25732,
    "region": "Oceania",
    "subregion": "Melanesia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "706",
    "cca2": "so",
    "cca3": "SOM",
    "name": "Somalia",
    "official": "Federal Republic of Somalia",
    "capital": "Mogadishu",
    "capitals": [
      "Mogadishu"
    ],
    "lon": 45.6796,
    "lat": 4.7397,
    "areaKm2": 473624,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "710",
    "cca2": "za",
    "cca3": "ZAF",
    "name": "South Africa",
    "official": "Republic of South Africa",
    "capital": "Pretoria",
    "capitals": [
      "Pretoria",
      "Bloemfontein",
      "Cape Town"
    ],
    "lon": 25.1937,
    "lat": -28.9743,
    "areaKm2": 1221613,
    "region": "Africa",
    "subregion": "Southern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "410",
    "cca2": "kr",
    "cca3": "KOR",
    "name": "South Korea",
    "official": "Republic of Korea",
    "capital": "Seoul",
    "capitals": [
      "Seoul"
    ],
    "lon": 127.835,
    "lat": 36.3735,
    "areaKm2": 97165,
    "region": "Asia",
    "subregion": "Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "728",
    "cca2": "ss",
    "cca3": "SSD",
    "name": "South Sudan",
    "official": "Republic of South Sudan",
    "capital": "Juba",
    "capitals": [
      "Juba"
    ],
    "lon": 30.2513,
    "lat": 7.3089,
    "areaKm2": 624000,
    "region": "Africa",
    "subregion": "Middle Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "724",
    "cca2": "es",
    "cca3": "ESP",
    "name": "Spain",
    "official": "Kingdom of Spain",
    "capital": "Madrid",
    "capitals": [
      "Madrid"
    ],
    "lon": -3.7036,
    "lat": 40.2076,
    "areaKm2": 506179,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "144",
    "cca2": "lk",
    "cca3": "LKA",
    "name": "Sri Lanka",
    "official": "Democratic Socialist Republic of Sri Lanka",
    "capital": "Colombo",
    "capitals": [
      "Colombo"
    ],
    "lon": 80.7016,
    "lat": 7.6114,
    "areaKm2": 66046,
    "region": "Asia",
    "subregion": "Southern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "729",
    "cca2": "sd",
    "cca3": "SDN",
    "name": "Sudan",
    "official": "Republic of the Sudan",
    "capital": "Khartoum",
    "capitals": [
      "Khartoum"
    ],
    "lon": 29.9073,
    "lat": 15.9681,
    "areaKm2": 1863032,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "740",
    "cca2": "sr",
    "cca3": "SUR",
    "name": "Suriname",
    "official": "Republic of Suriname",
    "capital": "Paramaribo",
    "capitals": [
      "Paramaribo"
    ],
    "lon": -55.9126,
    "lat": 4.13,
    "areaKm2": 145559,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "752",
    "cca2": "se",
    "cca3": "SWE",
    "name": "Sweden",
    "official": "Kingdom of Sweden",
    "capital": "Stockholm",
    "capitals": [
      "Stockholm"
    ],
    "lon": 16.2669,
    "lat": 62.3835,
    "areaKm2": 442971,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "756",
    "cca2": "ch",
    "cca3": "CHE",
    "name": "Switzerland",
    "official": "Swiss Confederation",
    "capital": "Bern",
    "capitals": [
      "Bern"
    ],
    "lon": 8.206,
    "lat": 46.7989,
    "areaKm2": 41215,
    "region": "Europe",
    "subregion": "Western Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "760",
    "cca2": "sy",
    "cca3": "SYR",
    "name": "Syria",
    "official": "Syrian Arab Republic",
    "capital": "Damascus",
    "capitals": [
      "Damascus"
    ],
    "lon": 38.4878,
    "lat": 35.019,
    "areaKm2": 185734,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "762",
    "cca2": "tj",
    "cca3": "TJK",
    "name": "Tajikistan",
    "official": "Republic of Tajikistan",
    "capital": "Dushanbe",
    "capitals": [
      "Dushanbe"
    ],
    "lon": 71.027,
    "lat": 38.5365,
    "areaKm2": 142300,
    "region": "Asia",
    "subregion": "Central Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "834",
    "cca2": "tz",
    "cca3": "TZA",
    "name": "Tanzania",
    "official": "United Republic of Tanzania",
    "capital": "Dodoma",
    "capitals": [
      "Dodoma"
    ],
    "lon": 34.802,
    "lat": -6.2685,
    "areaKm2": 945783,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "764",
    "cca2": "th",
    "cca3": "THA",
    "name": "Thailand",
    "official": "Kingdom of Thailand",
    "capital": "Bangkok",
    "capitals": [
      "Bangkok"
    ],
    "lon": 101.001,
    "lat": 15.0831,
    "areaKm2": 515721,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "626",
    "cca2": "tl",
    "cca3": "TLS",
    "name": "Timor-Leste",
    "official": "Democratic Republic of Timor-Leste",
    "capital": "Dili",
    "capitals": [
      "Dili"
    ],
    "lon": 125.8458,
    "lat": -8.8292,
    "areaKm2": 15018,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "768",
    "cca2": "tg",
    "cca3": "TGO",
    "name": "Togo",
    "official": "Togolese Republic",
    "capital": "Lomé",
    "capitals": [
      "Lomé"
    ],
    "lon": 0.9642,
    "lat": 8.5206,
    "areaKm2": 57156,
    "region": "Africa",
    "subregion": "Western Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "776",
    "cca2": "to",
    "cca3": "TON",
    "name": "Tonga",
    "official": "Kingdom of Tonga",
    "capital": "Nuku'alofa",
    "capitals": [
      "Nuku'alofa"
    ],
    "lon": -174.7998,
    "lat": -20.4161,
    "areaKm2": 431,
    "region": "Oceania",
    "subregion": "Polynesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "780",
    "cca2": "tt",
    "cca3": "TTO",
    "name": "Trinidad and Tobago",
    "official": "Republic of Trinidad and Tobago",
    "capital": "Port of Spain",
    "capitals": [
      "Port of Spain"
    ],
    "lon": -61.2661,
    "lat": 10.4567,
    "areaKm2": 5102,
    "region": "Americas",
    "subregion": "Caribbean",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "788",
    "cca2": "tn",
    "cca3": "TUN",
    "name": "Tunisia",
    "official": "Tunisian Republic",
    "capital": "Tunis",
    "capitals": [
      "Tunis"
    ],
    "lon": 9.5561,
    "lat": 34.0889,
    "areaKm2": 156653,
    "region": "Africa",
    "subregion": "Northern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "792",
    "cca2": "tr",
    "cca3": "TUR",
    "name": "Türkiye",
    "official": "Republic of Türkiye",
    "capital": "Ankara",
    "capitals": [
      "Ankara"
    ],
    "lon": 35.1735,
    "lat": 39.1369,
    "areaKm2": 779799,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "795",
    "cca2": "tm",
    "cca3": "TKM",
    "name": "Turkmenistan",
    "official": "Turkmenistan",
    "capital": "Ashgabat",
    "capitals": [
      "Ashgabat"
    ],
    "lon": 59.4465,
    "lat": 39.1254,
    "areaKm2": 470601,
    "region": "Asia",
    "subregion": "Central Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "798",
    "cca2": "tv",
    "cca3": "TUV",
    "name": "Tuvalu",
    "official": "Tuvalu",
    "capital": "Funafuti",
    "capitals": [
      "Funafuti"
    ],
    "lon": 178.5283,
    "lat": -7.7687,
    "areaKm2": 24,
    "region": "Oceania",
    "subregion": "Polynesia",
    "hasPolygon": false,
    "micro": true
  },
  {
    "id": "800",
    "cca2": "ug",
    "cca3": "UGA",
    "name": "Uganda",
    "official": "Republic of Uganda",
    "capital": "Kampala",
    "capitals": [
      "Kampala"
    ],
    "lon": 32.369,
    "lat": 1.2741,
    "areaKm2": 242569,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "804",
    "cca2": "ua",
    "cca3": "UKR",
    "name": "Ukraine",
    "official": "Ukraine",
    "capital": "Kyiv",
    "capitals": [
      "Kyiv"
    ],
    "lon": 31.3156,
    "lat": 49.1956,
    "areaKm2": 570137,
    "region": "Europe",
    "subregion": "Eastern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "784",
    "cca2": "ae",
    "cca3": "ARE",
    "name": "United Arab Emirates",
    "official": "United Arab Emirates",
    "capital": "Abu Dhabi",
    "capitals": [
      "Abu Dhabi"
    ],
    "lon": 54.2927,
    "lat": 23.9051,
    "areaKm2": 71265,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "826",
    "cca2": "gb",
    "cca3": "GBR",
    "name": "United Kingdom",
    "official": "United Kingdom of Great Britain and Northern Ireland",
    "capital": "London",
    "capitals": [
      "London"
    ],
    "lon": -2.7578,
    "lat": 54.0113,
    "areaKm2": 239616,
    "region": "Europe",
    "subregion": "Northern Europe",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "840",
    "cca2": "us",
    "cca3": "USA",
    "name": "United States",
    "official": "United States of America",
    "capital": "Washington D.C.",
    "capitals": [
      "Washington D.C."
    ],
    "lon": -98.8163,
    "lat": 39.8944,
    "areaKm2": 9439451,
    "region": "Americas",
    "subregion": "North America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "858",
    "cca2": "uy",
    "cca3": "URY",
    "name": "Uruguay",
    "official": "Oriental Republic of Uruguay",
    "capital": "Montevideo",
    "capitals": [
      "Montevideo"
    ],
    "lon": -56.0252,
    "lat": -32.7913,
    "areaKm2": 177570,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "860",
    "cca2": "uz",
    "cca3": "UZB",
    "name": "Uzbekistan",
    "official": "Republic of Uzbekistan",
    "capital": "Tashkent",
    "capitals": [
      "Tashkent"
    ],
    "lon": 63.3027,
    "lat": 41.7755,
    "areaKm2": 447382,
    "region": "Asia",
    "subregion": "Central Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "548",
    "cca2": "vu",
    "cca3": "VUT",
    "name": "Vanuatu",
    "official": "Republic of Vanuatu",
    "capital": "Port Vila",
    "capitals": [
      "Port Vila"
    ],
    "lon": 167.6752,
    "lat": -16.2169,
    "areaKm2": 11266,
    "region": "Oceania",
    "subregion": "Melanesia",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "336",
    "cca2": "va",
    "cca3": "VAT",
    "name": "Vatican City",
    "official": "Vatican City State",
    "capital": "Vatican City",
    "capitals": [
      "Vatican City"
    ],
    "lon": 12.4343,
    "lat": 41.9021,
    "areaKm2": 1,
    "region": "Europe",
    "subregion": "Southern Europe",
    "hasPolygon": true,
    "micro": true
  },
  {
    "id": "862",
    "cca2": "ve",
    "cca3": "VEN",
    "name": "Venezuela",
    "official": "Bolivarian Republic of Venezuela",
    "capital": "Caracas",
    "capitals": [
      "Caracas"
    ],
    "lon": -66.1707,
    "lat": 7.1223,
    "areaKm2": 914313,
    "region": "Americas",
    "subregion": "South America",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "704",
    "cca2": "vn",
    "cca3": "VNM",
    "name": "Vietnam",
    "official": "Socialist Republic of Vietnam",
    "capital": "Hanoi",
    "capitals": [
      "Hanoi"
    ],
    "lon": 106.3465,
    "lat": 16.5438,
    "areaKm2": 328960,
    "region": "Asia",
    "subregion": "South-Eastern Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "887",
    "cca2": "ye",
    "cca3": "YEM",
    "name": "Yemen",
    "official": "Republic of Yemen",
    "capital": "Sana'a",
    "capitals": [
      "Sana'a"
    ],
    "lon": 47.5676,
    "lat": 15.9172,
    "areaKm2": 454140,
    "region": "Asia",
    "subregion": "Western Asia",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "894",
    "cca2": "zm",
    "cca3": "ZMB",
    "name": "Zambia",
    "official": "Republic of Zambia",
    "capital": "Lusaka",
    "capitals": [
      "Lusaka"
    ],
    "lon": 27.8088,
    "lat": -13.4554,
    "areaKm2": 755595,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  },
  {
    "id": "716",
    "cca2": "zw",
    "cca3": "ZWE",
    "name": "Zimbabwe",
    "official": "Republic of Zimbabwe",
    "capital": "Harare",
    "capitals": [
      "Harare"
    ],
    "lon": 29.8509,
    "lat": -18.9969,
    "areaKm2": 390203,
    "region": "Africa",
    "subregion": "Eastern Africa",
    "hasPolygon": true,
    "micro": false
  }
] as const;

/** ISO numeric ids present in the topology that are never a legal guess or target. */
export const INERT_IDS: ReadonlySet<string> = new Set(["010","016","060","086","092","136","158","184","234","238","239","248","258","260","304","316","334","344","446","500","531","533","534","540","570","574","580","612","630","652","654","660","663","666","732","796","831","832","833","850","876"]);

/** Unidentified topology features (disputed / non-state), matched by Natural Earth name. */
export const INERT_NAMES: ReadonlySet<string> = new Set(["Indian Ocean Ter.","Kosovo","N. Cyprus","Siachen Glacier","Somaliland"]);

/** Countries too small to reliably tap at world zoom — the renderer gives them markers. */
export const MICRO_STATE_AREA_KM2 = 12000;
